---
title: "`{r} pkg_name`: `{r} packageDescription(pkg_name, fields = 'Title')`"
date: "`{r} Sys.Date()`"
output:
  html:
---

```{r, order = 0}
litedown::reactor(echo = FALSE)
# package description
pkg_name = local({
    old <- setwd("../pkg")
    tryCatch(litedown:::detect_pkg(), finally = setwd(old))
})
pkg_path = attr(pkg_name, 'path')
litedown::pkg_desc(pkg_name)
```

```{r, results = 'asis'}
# readme, if exists
if (file.exists(readme <- file.path(pkg_path, 'README.md'))) {
  x = xfun::read_utf8(readme)
  i = which(x == '<!-- badges: start -->')
  # remove lines before badges since they usually contain duplicated info (e.g., title)
  if (length(i)) x = x[-seq_len(i[1] - 1)]
  # if man/figures exists and used, copy it to current dir
  fig = file.path(pkg_path, fig_man <- 'man/figures')
  if (any(grepl(fig_man, x)) && dir.exists(figures)) {
    xfun::dir_create('man')
    file.copy(figures, 'man', recursive = TRUE)
  }
  xfun::raw_string(x)
}
```

## Vignettes
A detailed introduction to grates can be found in the included vignette

```{r, echo = FALSE, results = 'asis'}
pkg_name = local({
    old <- setwd("../pkg")
    tryCatch(litedown:::detect_pkg(), finally = setwd(old))
})
res = tools::getVignetteInfo(pkg_name)
res = if (nrow(res)) {
  file.copy(system.file('doc', package = pkg_name), './', recursive = TRUE)
  vigs = res[, 'PDF']
  # redirect doc/index.html to article.html
  if (!'index.html' %in% vigs) writeLines(
    "<script>location.href = location.href.replace(/\\/[^\\/]*$/, '') + '/../articles.html';</script>", 'doc/index.html'
  )
  # clean up .R files
  file.remove(file.path('doc', setdiff(res[, 'R'], '')))
  src = res[, 'File']
  # TODO: show excerpts of vignettes if possible
  sprintf('- [%s](doc/%s) (source: [%s](doc/%s))\n', res[, 'Title'], vigs, src, src)
} else 'This package has no vignettes.'
xfun::raw_string(res)
```
