# nocov start
.onLoad <- function(...) {
    s3_register("vctrs::vec_ptype_abbr", "grates_month")
    s3_register("vctrs::vec_ptype_full", "grates_month")
    s3_register("vctrs::vec_ptype_abbr", "grates_period")
    s3_register("vctrs::vec_ptype_full", "grates_period")
    s3_register("vctrs::vec_ptype_abbr", "grates_isoweek")
    s3_register("vctrs::vec_ptype_full", "grates_isoweek")
    s3_register("vctrs::vec_ptype_abbr", "grates_epiweek")
    s3_register("vctrs::vec_ptype_full", "grates_epiweek")
    s3_register("vctrs::vec_ptype_abbr", "grates_yearweek")
    s3_register("vctrs::vec_ptype_full", "grates_yearweek")
    s3_register("vctrs::vec_ptype_full", "grates_yearweek_monday")
    s3_register("vctrs::vec_ptype_full", "grates_yearweek_tuesday")
    s3_register("vctrs::vec_ptype_full", "grates_yearweek_wednesday")
    s3_register("vctrs::vec_ptype_full", "grates_yearweek_thursday")
    s3_register("vctrs::vec_ptype_full", "grates_yearweek_friday")
    s3_register("vctrs::vec_ptype_full", "grates_yearweek_saturday")
    s3_register("vctrs::vec_ptype_full", "grates_yearweek_sunday")
    s3_register("vctrs::vec_ptype_abbr", "grates_yearmonth")
    s3_register("vctrs::vec_ptype_full", "grates_yearmonth")
    s3_register("vctrs::vec_ptype_abbr", "grates_yearquarter")
    s3_register("vctrs::vec_ptype_full", "grates_yearquarter")
    s3_register("vctrs::vec_ptype_abbr", "grates_year")
    s3_register("vctrs::vec_ptype_full", "grates_year")

    s3_register("ggplot2::scale_type", "grates_month")
    s3_register("ggplot2::scale_type", "grates_period")
    s3_register("ggplot2::scale_type", "grates_epiweek")
    s3_register("ggplot2::scale_type", "grates_isoweek")
    s3_register("ggplot2::scale_type", "grates_yearweek")
    s3_register("ggplot2::scale_type", "grates_yearmonth")
    s3_register("ggplot2::scale_type", "grates_yearquarter")
    s3_register("ggplot2::scale_type", "grates_year")

    invisible()
}
# nocov end
